version: "3"
services: 
   
    wks_php_7_2:
        build: 
            context: ./images/php7.2
            args:
                USER_ID: 1000
                GROUP_ID: 1000
        container_name: wks_php_7_2
        environment:
            - TZ=America/Sao_Paulo
            - DEBIAN_FRONTEND=noninteractive
        stdin_open: true
        tty: true
        volumes: 
            - "./www:/app/www"

    wks_php_8_1:
        build: 
            context: ./images/php8.1
            args:
                USER_ID: 1000
                GROUP_ID: 1000
        container_name: wks_php_8_1
        environment:
            - TZ=America/Sao_Paulo
            - DEBIAN_FRONTEND=noninteractive
        stdin_open: true
        tty: true
        volumes: 
            - "./www:/app/www"        

    wks_node_18:
        build:
            context: ./images/node18
            args:
                USER_ID: 1000
                GROUP_ID: 1000
        container_name: wks_node18
        environment:
            - TZ=America/Sao_Paulo
            - DEBIAN_FRONTEND=noninteractive
        stdin_open: true
        tty: true
        volumes: 
            - "./www:/app/www"
        ports:
            - "8080:8080"
            - "3000:3000"        

networks:
    default:
        external: false
        name: php_dev
