version: "3.5"
services:
    db:
        image: mysql:8.0
        container_name: mysql_8
        command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        ports:
            - "3306:3306"
        volumes:
            - ./storage:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
networks:
    default:
        external: false
        name: php_dev
