version: "3.5"
services:
    db:
        image: mysql:5.7
        container_name: mysql_5_7
        ports:
            - "3306:3306"
        volumes:
            - ./storage:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
networks:
    default:
        external: false
        name: php_dev
