version: "3.5"
services:
    # Web service layer
    # 80:80 host:container
    nginx:
        container_name: server_nginx
        image: nginx:latest
        volumes: 
            - "../projects/www:/var/www/html"
            - "./nginx.conf:/etc/nginx/nginx.conf"
            - "./sites:/etc/nginx/sites-available"
            - "./logs:/var/log/nginx"
        ports:
            - "80:80"
        networks: 
            default: 
                aliases: # Custom hosts config inside network, all requests for theses domains will go to this container
                    - api.*
networks:
    default:
        external: true
        name: php_dev